---
output:
  html_document:
    css: ~/KaplanFiles/DCF-Course-2014/CSS/DCF-Course-style.css
    fig_caption: yes
    toc: no
---

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

```{r include=FALSE}
Notes <- function(topic,name="DraftNarrative.html") {
  prename <- "http://dtkaplan.github.io/DCF-2014/CourseNotes"
  return(I(paste( prename, topic, name, sep="/")))
} 
Assignment <- function(name="Assignment-One.html") {
  prename <- "http://dtkaplan.github.io/DCF-2014/Assignments"
  return(I(paste(prename, name, sep="/")))
}
Drill <- function(name="Week-1.html") {
  prename <- "http://dtkaplan.github.io/DCF-2014/Drill"
  return(I(paste(prename, name, sep="/")))
}
````

<h2>Data & Computing Fundamentals: COMP 110</h2> 

<div class="subtitle">Fall 2014, Macalester College, Prof. Daniel Kaplan</div>

DCF is a seven-week, one-credit hour course.  It's intended to provide an introduction to the technology of data appropriate for natural and social science in the 21st century. 

<hr class="syllabus">

<div class="container">
 <div class="row">
  <div class="col-sm-6 col-md-4 col-lg-3">
  
<h4>Resources</h4>

* [Course Policies and Structure](Background/StructureAndPolicies.html)
* 1-page guide to ["Enough R for DCF"](`r Notes("Guides","EnoughDCF.pdf")`)
* Tips on [refining `ggplot()` graphics](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/) ... [data source](http://www.ihapss.jhsph.edu/data/NMMAPS/Data/data_download_gz.htm)
* [Templates for Graphics](`r Notes( "GraphingIntro", "GraphicsTemplates.html")`)
* [Weekly Goals](Background/WeeklyGoals.html)
* [FAQ](Notes/FAQ.html)
* [Macalester RStudio cloud server](http://www.macalester.edu/rstudio)
* [Installing the DCF package](Background/Installing-DCF.html).
* Contact Us:
    - Danny Kaplan <kaplan@macalester.edu>
    - Erik Anderson <ande7564@umn.edu>
    - **HELP!** Available each evening with the HHMI Stats Fellows in Olin-Rice 245. Sun. through Thurs. 7:00-9:30pm.
* Videos from the Amherst/5-College R/RStudio series: [link](http://www3.amherst.edu/~nhorton/rstudio/)  
  </div>
  <div class="col-sm-6 col-md-4 col-lg-3">

<h4 title="Wed. 10 Sept.">Week 1   &nbsp;<span style="float:right;">Sept. 10</span></h4> 

Infrastructure for computing with data. [Goals for the week.](Background/WeeklyGoals.html#week-1)

**Before Class**   

* Notes:    
    [Structure of Data](`r Notes("DataOrganization")`),
    [A Quick Start with R](`r Notes("Rbasics","R-Basics.html")`),
    [Paths and File Types](`r Notes("DataOrganization", "FileTypes.html")`)
    
* Videos (optional): Logging in to the RStudio server [I](https://www.youtube.com/watch?v=3Y_i3PxIKfg&feature=youtu.be) & [II](https://www.youtube.com/watch?v=cr5KR4wmb2U&feature=youtu.be).  R/Markdown [I](http://youtu.be/w4hLT7WyjnM) & [II](http://youtu.be/MdxNFiXm1qE).

* [Weekly Drill](`r Drill("Week-1.html")`)
* [Weekly Discussion Posts](Week-1-Discussion.html)
  
**In Class and After** 

[Notes from Class](Notes/Week-1/Week-1-Notes.html)
  
[Assignment 1](`r Assignment("Assignment-One")`) due Fri. Sept. 20. [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19069)
  </div>
  <div class="clearfix visible-sm-block"></div>
   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4 title="Wed. 17 Sept." >Week 2  &nbsp; <span style="float:right;">Sept. 17</span></h4>
Data summaries and graphics. [Goals for the Week](Background/WeeklyGoals.html#week-2)
   
**Before Class**   

* Notes: 
    [R Commands](`r Notes("Rbasics")`), 
    [Data Verbs](`r Notes("BasicDataCommands")`),
    [BasicGraphics](`r Notes("GraphicsConstructDeconstruct")`),
    [Glyphs, Frames, and Guides](`r Notes("GraphicsConstructDeconstruct","Glyphs.html")`)  

* [Weekly Drill](`r Drill("Week-2.html")`)
* [Weekly Discussion Posts](Week-2-Discussion.html)
  
**In Class and After**    
  
[Notes from Class](Notes/Week-2/Week-2-Notes.html) and [graphics worksheet](http://dtkaplan.github.io/DCF-2014/Exercises/ParsingGraphics/PDF-2014-09-17-DTK-101.pdf)

[Assignment 2](`r Assignment("Assignment-Two")`) due 24 Sept. [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19070)

   </div>
   <div class="clearfix visible-md-block"></div>

<hr class="syllabus">

   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4 title="Oct. 1" >Week 3  &nbsp;<span style="float:right;">Oct. 1</span></h4>

Data Verbs  [Goals for the Week](Background/WeeklyGoals.html#week-3)

**Before Class**   

* Notes: 
    [More Data Verbs](`r Notes("BasicDataCommands","MoreDataVerbs.html")`), details on a special data verb: [Join](`r Notes("BasicDataCommands", "Join.html")`), [Graphics: Facets and Layers](`r Notes("GraphingIntro", "GraphicsCommands.html")`)  

* [Weekly Drill](`r Drill("Week-3.html")`)
* [Weekly Discussion Posts](Week-3-Discussion.html)
  
**In Class and After**    
  
* [Assignment 3](`r Assignment("Assignment-Three")`) due 8 Oct. [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19072)
* In-class activity:  [baby names](Notes/Week-3-Handout.pdf)

   </div>
   <div class="clearfix visible-sm-block"></div>
   <div class="clearfix visible-lg-block"></div>
   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4 class="this-week">Week 4  &nbsp; <span style="float:right;">Oct. 8<span></h4>
Data BackStory [Goals for the Week](Background/WeeklyGoals.html#week-4)

**Before Class**   

* Notes:  [Wide versus Narrow](`r Notes("WideAndNarrow")`),  [Within-group Operations](`r Notes("BasicDataCommands","WithinGroupOperations.html")`), [Ranks](`r Notes("Rank")`), [Graphing Networks](`r Notes("Networks", "Networks.html")`)

* [Weekly Drill](`r Drill("Week-4.html")`)
* [Weekly Discussion Posts](Week-4-Discussion.html)
  
**In Class and After**    
  
[Assignment 4](`r Assignment("Assignment-Four")`) due TBA [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19073)

   </div>
   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4>Week 5  &nbsp;<span style="float:right;">Oct. 16</span></h4>
   
Stats and Properties of Cases Collectively. [Goals for the Week](Background/WeeklyGoals.html#week-5)

   
**Before Class**   

* Notes: [Graphics Choices](`r Notes("GraphicsChoices","DraftNarrative.html")`), [Distributions & Statistics](`r Notes("Stats","DraftNarrative.html")`)
 

* [Weekly Drill](`r Drill("Week-5.html")`)
* [Weekly Discussion Posts](Week-5-Discussion.html)
  
**In Class and After**    
  
[Assignment 5](`r Assignment("Assignment-Five")`) due TBA [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19074)

 
   </div>
<hr class="syllabus">

   <div class="clearfix visible-sm-block"></div>
   <div class="clearfix visible-md-block"></div>

   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4>Week 6   &nbsp;<span style="float:right;">Oct. 29</span></h4>

Working with many variables. [Goals for the Week](Background/WeeklyGoals.html#week-6)
   
**Before Class**   

* Notes: 
 

* [Weekly Drill](`r Drill("Week-6.html")`)
* [Weekly Discussion Posts](Week-6-Discussion.html)
  
**In Class and After**    
  
[Assignment 6](`r Assignment("Assignment-Six")`) due TBA. [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19075)

   </div>
   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4>Week 7   &nbsp; <span style="float:right;">Nov. 5</span></h4>
Cleaning and Scraping. [Goals for the Week](Background/WeeklyGoals.html#week-7)

**Before Class**   

* Notes: 
 

* [Weekly Drill](`r Drill("Week-7.html")`)
* [Weekly Discussion Posts](Week-7-Discussion.html)
  
**In Class and After**    
  
[Assignment 7](`r Assignment("Assignment-Seven")`) [Hand in here.](https://moodle.macalester.edu/mod/assign/view.php?id=19076)
   
   </div>
   <div class="clearfix visible-sm-block"></div>
   <div class="clearfix visible-lg-block"></div>
   <div class="col-sm-6 col-md-4 col-lg-3">
   <h4>Wrapping-up</h4>

* Exam
* Handing in the final assignment.

   </div>
   <div class="clearfix visible-md-block"></div>
  </div>
 </div>

<hr class="syllabus">

Development of the course is supported by a grant to Macalester College from the Howard Hughes Medical Institute.  The Mosaic Project is supported by the US National Science Foundation (DUE-0920350).



